spring.application.name=ArchSpot-BackEnd
spring.profiles.active=test


# ## ** BANCO H2 **
# # Configuração do banco H2
# spring.datasource.url=jdbc:h2:mem:meubanco
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# # H2 Console (interface web do banco)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# # JPA/Hibernate
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update

## ** banco MySQL **
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Limite máximo do arquivo (opcional)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Caminho temporário de upload (opcional)
spring.servlet.multipart.location=./uploads/tmp

# Chave secreta usada para assinar tokens (Tirar daqui quando for de verdade)
api.security.token.secret=${JWT_SECRET:mysupersecretkey}
