package com.archspot.ArchSpot_BackEnd.activities.enums;

public enum ActivityType {
    PHASE_CREATED,
    PHASE_UPDATED,
    PHASE_STARTED,
    PHASE_FINISHED,

    INSTALLMENT_CREATED,
    INSTALLMENT_UPDATED,
    INSTALLMENT_PAID,

    DOCUMENT_UPLOADED,
    DOCUMENT_INFO_UPDATED,
    DOCUMENT_VERSIONED,
    DOCUMENT_DELETED,

    PHOTO_UPLOADED,
    PHOTO_UPDATED,
    PHOTO_DELETED,

    USER_ASSIGNED_TO_PROJECT,
    USER_REMOVED_FROM_PROJECT,
    USER_ROLE_UPDATED,

    COMMENT_ADDED,
    COMMENT_DELETED,

    PROJECT_UPDATED,
    PROJECT_FINALIZED,
    PROJECT_CANCELLED,
}
