package com.archspot.ArchSpot_BackEnd.activities.enums;

public enum ActivityType {
    PHASE_CREATED,
    PHASE_UPDATED,
    PHASE_STARTED,
    PHASE_FINISHED,

    INSTALLMENT_CREATED,
    INSTALLMENT_PAID,

    PROJECT_FINALIZED,
    PROJECT_CANCELLED,

    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,

    PHOTO_UPLOADED,
    PHOTO_DELETED,

    COMMENT_ADDED,
    COMMENT_DELETED
}
